'use client'
import { useEffect, useRef, useState } from 'react'
import Sidebar from '@/components/Sidebar'
import { supabase } from '@/lib/supabase'
import { slugify } from '@/lib/utils'
import { ExternalLink, Search, AlertTriangle, Check, Copy, Upload, Download } from 'lucide-react'

type CourseListItem = { id: string; name: string; host_name: string | null; is_published: boolean; use_custom_override: boolean }
type CourseDetail = {
  id: string; name: string; host_name: string | null; slug: string | null
  is_published: boolean; use_custom_override: boolean; custom_page_override: string | null
}

export default function AdminCustomPagePage() {
  const [token, setToken] = useState('')
  const [authError, setAuthError] = useState('')

  const [search, setSearch] = useState('')
  const [courses, setCourses] = useState<CourseListItem[]>([])
  const [loadingList, setLoadingList] = useState(true)

  const [selectedId, setSelectedId] = useState('')
  const [detail, setDetail] = useState<CourseDetail | null>(null)
  const [initialContent, setInitialContent] = useState('') // what was actually saved, for the overwrite check
  const [content, setContent] = useState('')               // live edit buffer
  const [enabled, setEnabled] = useState(false)
  const [loadingDetail, setLoadingDetail] = useState(false)

  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [savedMsg, setSavedMsg] = useState(false)
  const [copiedMsg, setCopiedMsg] = useState('')
  const [confirmingReplace, setConfirmingReplace] = useState(false)
  const [exporting, setExporting] = useState(false)

  const fileInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    async function init() {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session?.access_token) {
        setAuthError('Not signed in.')
        setLoadingList(false)
        return
      }
      setToken(session.access_token)
      await loadList(session.access_token, '')
    }
    init()
  }, [])

  async function loadList(authToken: string, searchTerm: string) {
    setLoadingList(true)
    const res = await fetch(`/api/admin/custom-page?search=${encodeURIComponent(searchTerm)}`, {
      headers: { Authorization: `Bearer ${authToken}` },
    })
    const data = await res.json()
    if (res.ok) {
      setCourses(data.courses || [])
      setAuthError('')
    } else {
      setAuthError(data.error || 'Failed to load courses.')
    }
    setLoadingList(false)
  }

  async function selectCourse(courseId: string) {
    setSelectedId(courseId)
    setLoadingDetail(true)
    setError('')
    setConfirmingReplace(false)
    const res = await fetch(`/api/admin/custom-page?courseId=${courseId}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const data = await res.json()
    setLoadingDetail(false)
    if (!res.ok) { setError(data.error || 'Failed to load course.'); return }
    setDetail(data.course)
    setInitialContent(data.course.custom_page_override || '')
    setContent(data.course.custom_page_override || '')
    setEnabled(data.course.use_custom_override === true)
  }

  // True only when saving would actually destroy a previously saved custom
  // version — i.e. there WAS content, and it's different from what's about
  // to be saved. This is the exact case Nancy asked to be warned about.
  const wouldOverwriteExisting = initialContent.trim().length > 0 && content.trim() !== initialContent.trim()

  function copyToClipboard(text: string, label: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedMsg(label)
      setTimeout(() => setCopiedMsg(''), 2500)
    })
  }

  async function handleExportAutoGenerated() {
    if (!detail) return
    setExporting(true)
    setError('')
    const res = await fetch(`/api/admin/custom-page?exportCourseId=${detail.id}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const data = await res.json()
    setExporting(false)
    if (!res.ok) { setError(data.error || 'Export failed.'); return }
    copyToClipboard(data.html, 'Auto-generated page copied — paste it into your LLM chat')
  }

  function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => setContent(String(reader.result || ''))
    reader.readAsText(file)
    e.target.value = '' // allow re-uploading the same filename later
  }

  async function handleSave() {
    if (!detail) return

    if (wouldOverwriteExisting && !confirmingReplace) {
      setConfirmingReplace(true)
      return
    }

    setSaving(true)
    setError('')
    const res = await fetch('/api/admin/custom-page', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ courseId: detail.id, customPageOverride: content, useCustomOverride: enabled }),
    })
    const data = await res.json()
    setSaving(false)
    setConfirmingReplace(false)
    if (!res.ok) { setError(data.error || 'Save failed.'); return }
    setCourses(prev => prev.map(c => c.id === detail.id ? { ...c, use_custom_override: enabled } : c))
    setInitialContent(content)
    setSavedMsg(true)
    setTimeout(() => setSavedMsg(false), 2500)
  }

  const previewUrl = detail
    ? `/about-course/${slugify(detail.host_name || 'instructor')}/${slugify(detail.name)}/${detail.id}`
    : ''

  return (
    <div className="min-h-screen bg-black">
      <Sidebar />
      <main className="md:ml-56 p-6 md:p-8 max-w-6xl">
        <h1 className="text-2xl font-bold text-white mb-1">Custom Page Override</h1>
        <p className="text-sm mb-8" style={{ color: '#a1a1aa' }}>
          Admin-only. Replaces a single course's entire landing page with raw HTML you paste in — the shared
          auto-generation system every other creator uses is completely untouched.
        </p>

        {authError && (
          <div className="p-4 rounded-xl text-sm mb-6" style={{ background: 'rgba(239,68,68,0.08)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}>
            {authError}
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-6">

          {/* ── COURSE PICKER ── */}
          <div className="rounded-2xl p-4 glass" style={{ border: '1px solid rgba(255,255,255,0.06)', height: 'fit-content' }}>
            <div className="flex items-center gap-2 mb-3 px-1">
              <Search className="w-3.5 h-3.5" style={{ color: '#52525b' }} />
              <input value={search}
                onChange={e => { setSearch(e.target.value); loadList(token, e.target.value) }}
                placeholder="Search course name..."
                className="w-full bg-transparent text-sm text-white placeholder:text-zinc-600 outline-none" />
            </div>
            <div className="flex flex-col gap-1 max-h-[70vh] overflow-y-auto">
              {loadingList && <div className="text-xs px-2 py-3" style={{ color: '#52525b' }}>Loading...</div>}
              {!loadingList && courses.length === 0 && <div className="text-xs px-2 py-3" style={{ color: '#52525b' }}>No courses found.</div>}
              {courses.map(c => (
                <button key={c.id} type="button" onClick={() => selectCourse(c.id)}
                  className="text-left px-3 py-2.5 rounded-lg text-sm transition-all"
                  style={{
                    background: selectedId === c.id ? 'rgba(124,58,237,0.12)' : 'transparent',
                    color: selectedId === c.id ? '#fff' : '#a1a1aa',
                  }}>
                  <div className="flex items-center gap-2">
                    <span className="truncate">{c.name}</span>
                    {c.use_custom_override && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded-full flex-shrink-0" style={{ background: 'rgba(124,58,237,0.2)', color: '#a78bfa' }}>custom</span>
                    )}
                  </div>
                  <div className="text-xs truncate" style={{ color: '#52525b' }}>{c.host_name || 'No host name'}</div>
                </button>
              ))}
            </div>
          </div>

          {/* ── EDITOR ── */}
          <div className="flex flex-col gap-4">
            {!detail && (
              <div className="rounded-2xl p-8 glass text-center" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
                <p className="text-sm" style={{ color: '#71717a' }}>Select a course from the list to edit its custom page.</p>
              </div>
            )}

            {loadingDetail && <div className="text-sm" style={{ color: '#71717a' }}>Loading course...</div>}

            {detail && !loadingDetail && (
              <>
                <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
                  <div className="flex items-center justify-between mb-1">
                    <h2 className="font-semibold text-white">{detail.name}</h2>
                    <a href={previewUrl} target="_blank" rel="noopener noreferrer"
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium"
                      style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
                      <ExternalLink className="w-3 h-3" /> View live page
                    </a>
                  </div>
                  <p className="text-xs" style={{ color: '#52525b' }}>{detail.host_name || 'No host name'} · {detail.is_published ? 'Published' : 'Draft'}</p>

                  <div className="flex items-center gap-3 mt-5 p-4 rounded-xl" style={{ background: enabled ? 'rgba(124,58,237,0.08)' : 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)' }}>
                    <button type="button" onClick={() => setEnabled(v => !v)}
                      className="relative flex-shrink-0" style={{ width: 40, height: 22, borderRadius: 999, background: enabled ? '#7c3aed' : 'rgba(255,255,255,0.1)' }}>
                      <div className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all" style={{ left: enabled ? '20px' : '2px' }} />
                    </button>
                    <div className="flex-1">
                      <p className="text-sm font-semibold text-white">Use custom page for this course</p>
                      <p className="text-xs" style={{ color: '#71717a' }}>
                        When on, the HTML below completely replaces the normal auto-generated landing page. The
                        auto-generated page is never deleted — turning this off instantly reverts to it.
                      </p>
                    </div>
                  </div>
                </div>

                {/* ── STEP 1: get a copy of the current page to hand to an LLM ── */}
                <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
                  <h2 className="font-semibold text-white mb-1">1. Copy what to hand your LLM</h2>
                  <p className="text-xs mb-4" style={{ color: '#71717a' }}>
                    Grab a copy of whichever version is currently live, paste it into an LLM chat along with what
                    the creator wants changed, and bring the result back to step 2 below.
                  </p>
                  <div className="flex flex-wrap gap-2">
                    <button type="button" onClick={handleExportAutoGenerated} disabled={exporting}
                      className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium disabled:opacity-50"
                      style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
                      <Download className="w-3.5 h-3.5" /> {exporting ? 'Exporting...' : 'Copy auto-generated page'}
                    </button>
                    {initialContent.trim().length > 0 && (
                      <button type="button" onClick={() => copyToClipboard(initialContent, 'Current custom version copied')}
                        className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium"
                        style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
                        <Copy className="w-3.5 h-3.5" /> Copy current custom version
                      </button>
                    )}
                  </div>
                  {copiedMsg && (
                    <p className="text-xs mt-2 flex items-center gap-1.5" style={{ color: '#22c55e' }}>
                      <Check className="w-3.5 h-3.5" /> {copiedMsg}
                    </p>
                  )}
                  <p className="text-xs mt-3" style={{ color: '#52525b' }}>
                    ⚠ The auto-generated export is a reference snapshot only — its buy button's code is stripped
                    (it depends on a live session that won't exist elsewhere). If your LLM builds a new page from
                    it, have it replace the buy button with a plain link instead.
                  </p>
                </div>

                {/* ── STEP 2: bring the new version back ── */}
                <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
                  <div className="flex items-center justify-between mb-1">
                    <h2 className="font-semibold text-white">2. Paste or upload the new version</h2>
                    <span className="text-xs" style={{ color: '#52525b' }}>{content.length.toLocaleString()} characters</span>
                  </div>
                  <p className="text-xs mb-3" style={{ color: '#71717a' }}>
                    Full standalone HTML document, including its own &lt;style&gt; tags. Rendered inside a sandboxed
                    iframe on the live page — any JS in here runs isolated from the rest of the site.
                  </p>

                  {wouldOverwriteExisting && (
                    <div className="flex items-start gap-2 mb-3 p-3 rounded-xl" style={{ background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.2)' }}>
                      <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: '#f59e0b' }} />
                      <div className="flex-1">
                        <p className="text-xs" style={{ color: '#f59e0b' }}>
                          Saving will replace the current custom version — it can't be recovered afterward. Copy it
                          first if you might want it back.
                        </p>
                        <button type="button" onClick={() => copyToClipboard(initialContent, 'Current custom version copied')}
                          className="text-xs font-semibold mt-1.5 underline" style={{ color: '#f59e0b' }}>
                          Copy the version that will be replaced
                        </button>
                      </div>
                    </div>
                  )}

                  <div className="flex items-center gap-2 mb-2">
                    <input ref={fileInputRef} type="file" accept=".html,text/html" className="hidden" onChange={handleFileUpload} />
                    <button type="button" onClick={() => fileInputRef.current?.click()}
                      className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium"
                      style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
                      <Upload className="w-3.5 h-3.5" /> Upload .html file
                    </button>
                    <span className="text-xs" style={{ color: '#52525b' }}>or paste directly below</span>
                  </div>

                  <textarea value={content} onChange={e => { setContent(e.target.value); setConfirmingReplace(false) }}
                    spellCheck={false}
                    placeholder="<!doctype html>&#10;<html>&#10;  <head>...&#10;  <style>...</style>&#10;  </head>&#10;  <body>...</body>&#10;</html>"
                    className="w-full rounded-xl p-4 text-xs bg-black border text-zinc-100 placeholder:text-zinc-700 resize-y"
                    style={{ borderColor: 'rgba(255,255,255,0.1)', minHeight: 420, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', lineHeight: 1.6 }}
                  />
                </div>

                {enabled && content.trim().length === 0 && (
                  <div className="flex items-start gap-2 p-3 rounded-xl" style={{ background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.2)' }}>
                    <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: '#f59e0b' }} />
                    <p className="text-xs" style={{ color: '#f59e0b' }}>
                      This is on but there's no HTML yet — the live page falls back to the normal auto-generated
                      page until you add content and save.
                    </p>
                  </div>
                )}

                {error && (
                  <div className="p-4 rounded-xl text-sm" style={{ background: 'rgba(239,68,68,0.08)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}>
                    {error}
                  </div>
                )}

                <button onClick={handleSave} disabled={saving}
                  className="w-full py-3 rounded-xl text-sm font-semibold text-white violet-gradient hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2">
                  {saving
                    ? 'Saving...'
                    : savedMsg
                    ? (<><Check className="w-4 h-4" /> Saved</>)
                    : confirmingReplace
                    ? 'Click again to replace & save'
                    : 'Save'}
                </button>
              </>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}