'use client'
import { useEffect, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { slugify } from '@/lib/utils'
import { ExternalLink, AlertTriangle, Check, Upload, Download, Sparkles, Code2, Eye, X } from 'lucide-react'

type CourseDetail = {
  id: string; name: string; host_name: string | null; slug: string | null
  is_published: boolean; use_custom_override: boolean; custom_page_override: string | null
}

type PreviewState = { label: string; filename: string; text: string } | null

export default function CustomPageOverrideEditor({ courseId }: { courseId: string }) {
  const [token, setToken] = useState('')
  const [userEmail, setUserEmail] = useState('')
  const [userName, setUserName] = useState('')
  const [authError, setAuthError] = useState('')
  const [detail, setDetail] = useState<CourseDetail | null>(null)
  const [initialContent, setInitialContent] = useState('') // what was actually saved, for the overwrite check
  const [content, setContent] = useState('')               // live edit buffer
  const [enabled, setEnabled] = useState(false)
  const [loadingDetail, setLoadingDetail] = useState(true)

  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [savedMsg, setSavedMsg] = useState(false)
  const [confirmingReplace, setConfirmingReplace] = useState(false)
  const [exporting, setExporting] = useState(false)

  // File download + inline preview — clipboard writes are unreliable here:
  // the browser only allows navigator.clipboard.writeText() during the
  // synchronous window right after a user click, and the export button has
  // to `await fetch(...)` first, which loses that window in Firefox (and
  // sometimes Safari), throwing NotAllowedError. Downloading a file has no
  // such restriction, and showing the content first is more useful anyway —
  // a creator can actually check what they're about to hand an LLM.
  const [preview, setPreview] = useState<PreviewState>(null)

  // "Request the team to update it for you" — free-form description + contact
  const [requestText, setRequestText] = useState('')
  const [sendingRequest, setSendingRequest] = useState(false)
  const [requestSent, setRequestSent] = useState(false)
  const [requestError, setRequestError] = useState('')

  const fileInputRef = useRef<HTMLInputElement>(null)
  const previewRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    async function init() {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session?.access_token) {
        setAuthError('Not signed in.')
        setLoadingDetail(false)
        return
      }
      setToken(session.access_token)
      setUserEmail(session.user?.email || '')
      setUserName(session.user?.user_metadata?.full_name || session.user?.user_metadata?.username || '')

      setLoadingDetail(true)
      const res = await fetch(`/api/course-custom-page?courseId=${courseId}`, {
        headers: { Authorization: `Bearer ${session.access_token}` },
      })
      const data = await res.json()
      setLoadingDetail(false)
      if (!res.ok) {
        setError(data.error || 'Failed to load course.')
        return
      }
      setDetail(data.course)
      setInitialContent(data.course.custom_page_override || '')
      setContent(data.course.custom_page_override || '')
      setEnabled(data.course.use_custom_override === true)
    }
    init()
  }, [courseId])

  useEffect(() => {
    if (preview) previewRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }, [preview])

  // True only when saving would actually destroy a previously saved custom
  // version — i.e. there WAS content, and it's different from what's about
  // to be saved.
  const wouldOverwriteExisting = initialContent.trim().length > 0 && content.trim() !== initialContent.trim()

  function downloadFile(text: string, filename: string) {
    const blob = new Blob([text], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  function openPreview(label: string, filename: string, text: string) {
    setPreview({ label, filename, text })
  }

  async function handleExportAutoGenerated() {
    if (!detail) return
    setExporting(true)
    setError('')
    const res = await fetch(`/api/course-custom-page?exportCourseId=${detail.id}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const data = await res.json()
    setExporting(false)
    if (!res.ok) { setError(data.error || 'Export failed.'); return }
    openPreview('Auto-generated page', `${slugify(detail.name)}-auto-generated.html`, data.html)
  }

  function handlePreviewCustomVersion() {
    if (!detail) return
    openPreview('Your custom version', `${slugify(detail.name)}-custom-version.html`, initialContent)
  }

  function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => setContent(String(reader.result || ''))
    reader.readAsText(file)
    e.target.value = '' // allow re-uploading the same filename later
  }

  async function persist(nextEnabled: boolean, nextContent: string) {
    if (!detail) return
    setSaving(true)
    setError('')
    const res = await fetch('/api/course-custom-page', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ courseId: detail.id, customPageOverride: nextContent, useCustomOverride: nextEnabled }),
    })
    const data = await res.json()
    setSaving(false)
    if (!res.ok) { setError(data.error || 'Save failed.'); return false }
    setEnabled(nextEnabled)
    setInitialContent(nextContent)
    setContent(nextContent)
    setSavedMsg(true)
    setTimeout(() => setSavedMsg(false), 2500)
    return true
  }

  async function handleSaveNewVersion() {
    if (!detail) return
    if (wouldOverwriteExisting && !confirmingReplace) {
      setConfirmingReplace(true)
      return
    }
    setConfirmingReplace(false)
    // Saving here keeps whichever version is currently live selected below —
    // it doesn't force-enable the custom version. Use the selector to switch.
    await persist(enabled, content)
  }

  // Selecting a version is its own action — flips `enabled` and saves
  // immediately, mutually exclusive with the other option.
  async function selectVersion(useCustom: boolean) {
    if (useCustom === enabled) return
    if (useCustom && content.trim().length === 0) {
      setError('Add your custom page content below before switching to it.')
      return
    }
    await persist(useCustom, content)
  }

  async function handleSendRequest() {
    if (!requestText.trim() || sendingRequest || !detail) return
    setSendingRequest(true)
    setRequestError('')
    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: userName || 'Kurso creator',
          email: userEmail || 'no-email-on-file@kurso.in',
          subject: 'landing_customization',
          message: `Course: ${detail.name} (${detail.id})\nLive page: ${previewUrl}\n\nWhat they want changed:\n${requestText.trim()}`,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Could not send your request.')
      setRequestSent(true)
      setRequestText('')
    } catch (err: any) {
      setRequestError(err.message || 'Could not send your request.')
    } finally {
      setSendingRequest(false)
    }
  }

  const previewUrl = detail
    ? `/about-course/${slugify(detail.host_name || 'instructor')}/${slugify(detail.name)}/${detail.id}`
    : ''

  if (authError) {
    return (
      <div className="p-4 rounded-xl text-sm" style={{ background: 'rgba(239,68,68,0.08)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}>
        {authError}
      </div>
    )
  }

  if (loadingDetail) {
    return <div className="text-sm" style={{ color: '#71717a' }}>Loading...</div>
  }

  if (!detail) {
    return (
      <div className="p-4 rounded-xl text-sm" style={{ background: 'rgba(239,68,68,0.08)', color: '#ef4444', border: '1px solid rgba(239,68,68,0.2)' }}>
        {error || 'Could not load this course.'}
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-5">

      {/* ── PREVIEW PANEL — shown before downloading anything ── */}
      {preview && (
        <div ref={previewRef} className="rounded-2xl p-6 glass" style={{ border: '2px solid var(--kurso-primary)' }}>
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Eye className="w-4 h-4" style={{ color: 'var(--kurso-primary-lighter)' }} />
              <h2 className="font-semibold text-white">{preview.label}</h2>
              <span className="text-xs" style={{ color: '#52525b' }}>{preview.text.length.toLocaleString()} characters</span>
            </div>
            <button onClick={() => setPreview(null)}
              className="w-8 h-8 flex items-center justify-center rounded-lg"
              style={{ background: 'rgba(255,255,255,0.06)', color: '#a1a1aa' }}>
              <X className="w-4 h-4" />
            </button>
          </div>
          <textarea readOnly value={preview.text}
            className="w-full rounded-xl p-4 text-xs bg-black border text-zinc-100 resize-y"
            style={{ borderColor: 'rgba(255,255,255,0.1)', minHeight: 320, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', lineHeight: 1.6 }}
          />
          <button onClick={() => downloadFile(preview.text, preview.filename)}
            className="w-full mt-3 py-2.5 rounded-xl text-sm font-semibold text-white violet-gradient hover:opacity-90 flex items-center justify-center gap-2">
            <Download className="w-4 h-4" /> Download
          </button>
        </div>
      )}

      {/* ── 1. REQUEST THE TEAM ── */}
      <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
        <div className="flex items-center gap-2 mb-1">
          <Sparkles className="w-4 h-4" style={{ color: 'var(--kurso-primary-lighter)' }} />
          <h2 className="font-semibold text-white">Want a fully custom design for this page?</h2>
        </div>
        <p className="text-xs mb-4" style={{ color: '#71717a' }}>
          Tell us how you want your course page to look and we'll build it for you — completely free, no extra cost.
        </p>
        <textarea value={requestText} onChange={e => { setRequestText(e.target.value); setRequestSent(false) }}
          placeholder="Describe the look, layout, or changes you want — e.g. 'a darker theme with a video at the top' or 'match the style of my Instagram page'..."
          rows={4}
          className="w-full px-3 py-2.5 rounded-lg text-sm bg-white/5 border border-white/10 text-white placeholder:text-zinc-600 resize-y mb-3" />
        {requestError && (
          <p className="text-xs mb-2" style={{ color: '#ef4444' }}>{requestError}</p>
        )}
        {requestSent ? (
          <div className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold w-fit"
            style={{ background: 'rgba(34,197,94,0.1)', color: '#22c55e', border: '1px solid rgba(34,197,94,0.2)' }}>
            <Check className="w-4 h-4" /> Request sent — we'll reach out soon
          </div>
        ) : (
          <button onClick={handleSendRequest} disabled={!requestText.trim() || sendingRequest}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold text-white violet-gradient hover:opacity-90 disabled:opacity-50">
            {sendingRequest ? 'Sending...' : 'Contact us — it\'s free'}
          </button>
        )}
      </div>

      {/* ── 2. FOR DEVELOPERS / VIBE CODERS ── */}
      <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
        <div className="flex items-center gap-2 mb-1">
          <Code2 className="w-4 h-4" style={{ color: 'var(--kurso-primary-lighter)' }} />
          <h2 className="font-semibold text-white">Prefer to build it yourself?</h2>
        </div>
        <p className="text-xs mb-3" style={{ color: '#71717a' }}>
          If you're a developer or comfortable "vibe coding" with an AI tool, you can do it yourself:
        </p>
        <ol className="flex flex-col gap-1.5 mb-2 text-xs" style={{ color: '#a1a1aa' }}>
          <li>1. Download your current page's code below</li>
          <li>2. Give it to an AI/LLM tool along with what you want changed</li>
          <li>3. Bring the new version back and upload or paste it here</li>
          <li>4. Something broke? Switch back to the auto-generated version any time — nothing is deleted</li>
          <li>5. Stuck, or want us to take it from here? Use the contact box above, anytime</li>
        </ol>
      </div>

      {/* ── 3. DOWNLOAD YOUR PAGE CODE ── */}
      <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
        <h2 className="font-semibold text-white mb-1">Download your page code</h2>
        <p className="text-xs mb-4" style={{ color: '#71717a' }}>
          Preview it first, then download the file — this is what you'll hand to your AI tool.
        </p>
        <div className="flex flex-wrap gap-2">
          <button type="button" onClick={handleExportAutoGenerated} disabled={exporting}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium disabled:opacity-50"
            style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
            <Eye className="w-3.5 h-3.5" /> {exporting ? 'Loading...' : 'Preview auto-generated page'}
          </button>
          {initialContent.trim().length > 0 && (
            <button type="button" onClick={handlePreviewCustomVersion}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium"
              style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
              <Eye className="w-3.5 h-3.5" /> Preview your custom version
            </button>
          )}
          <a href={previewUrl} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium"
            style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
            <ExternalLink className="w-3.5 h-3.5" /> View live page
          </a>
        </div>
        <p className="text-xs mt-3" style={{ color: '#52525b' }}>
          Note: the auto-generated export is a reference snapshot — its buy button's code and any video embed are
          stripped, since neither works once nested inside the sandboxed frame this becomes. Have your AI tool
          replace the buy button with a plain link, and any video with a link or thumbnail image.
        </p>
      </div>

      {/* ── 4. UPLOAD NEW VERSION ── */}
      <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
        <div className="flex items-center justify-between mb-1">
          <h2 className="font-semibold text-white">Bring your new version back</h2>
          <span className="text-xs" style={{ color: '#52525b' }}>{content.length.toLocaleString()} characters</span>
        </div>
        <p className="text-xs mb-3" style={{ color: '#71717a' }}>
          Full standalone HTML document, including its own &lt;style&gt; tags. It runs inside a sandboxed frame on
          your live page, isolated from the rest of the site.
        </p>

        {wouldOverwriteExisting && (
          <div className="flex items-start gap-2 mb-3 p-3 rounded-xl" style={{ background: 'rgba(var(--kurso-accent-rgb), 0.08)', border: '1px solid rgba(var(--kurso-accent-rgb), 0.2)' }}>
            <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: 'var(--kurso-accent)' }} />
            <div className="flex-1">
              <p className="text-xs" style={{ color: 'var(--kurso-accent)' }}>
                Saving will replace your current custom version — it can't be recovered afterward. Download it
                first if you might want it back.
              </p>
              <button type="button" onClick={handlePreviewCustomVersion}
                className="text-xs font-semibold mt-1.5 underline" style={{ color: 'var(--kurso-accent)' }}>
                Preview & download the version that will be replaced
              </button>
            </div>
          </div>
        )}

        <div className="flex items-center gap-2 mb-2">
          <input ref={fileInputRef} type="file" accept=".html,text/html" className="hidden" onChange={handleFileUpload} />
          <button type="button" onClick={() => fileInputRef.current?.click()}
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium"
            style={{ background: 'rgba(255,255,255,0.05)', color: '#a1a1aa', border: '1px solid rgba(255,255,255,0.08)' }}>
            <Upload className="w-3.5 h-3.5" /> Upload .html file
          </button>
          <span className="text-xs" style={{ color: '#52525b' }}>or paste directly below</span>
        </div>

        <textarea value={content} onChange={e => { setContent(e.target.value); setConfirmingReplace(false) }}
          spellCheck={false}
          placeholder="<!doctype html>&#10;<html>&#10;  <head>...&#10;  <style>...</style>&#10;  </head>&#10;  <body>...</body>&#10;</html>"
          className="w-full rounded-xl p-4 text-xs bg-black border text-zinc-100 placeholder:text-zinc-700 resize-y"
          style={{ borderColor: 'rgba(255,255,255,0.1)', minHeight: 320, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', lineHeight: 1.6 }}
        />

        {content.trim().length > 0 && content.trim() !== initialContent.trim() && (
          <button onClick={handleSaveNewVersion} disabled={saving}
            className="w-full mt-3 py-2.5 rounded-xl text-sm font-semibold text-white violet-gradient hover:opacity-90 disabled:opacity-50">
            {saving ? 'Saving...' : confirmingReplace ? 'Click again to replace & save' : 'Save this version'}
          </button>
        )}
      </div>

      {/* ── 5. WHICH VERSION IS LIVE ── */}
      <div className="rounded-2xl p-6 glass" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
        <h2 className="font-semibold text-white mb-1">Which version is live?</h2>
        <p className="text-xs mb-4" style={{ color: '#71717a' }}>
          Switch any time — your auto-generated page is never deleted, so you can always come back to it.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <button type="button" onClick={() => selectVersion(false)} disabled={saving}
            className="text-left p-4 rounded-xl transition-all disabled:opacity-50"
            style={{
              background: !enabled ? 'rgba(var(--kurso-primary-rgb), 0.1)' : 'rgba(255,255,255,0.02)',
              border: !enabled ? '2px solid var(--kurso-primary)' : '1px solid rgba(255,255,255,0.08)',
            }}>
            <div className="flex items-center gap-2 mb-1">
              <p className="text-sm font-semibold text-white">Auto-Generated</p>
              {!enabled && <Check className="w-4 h-4" style={{ color: 'var(--kurso-primary-light)' }} />}
            </div>
            <p className="text-xs" style={{ color: '#71717a' }}>Built from your theme, sections, and course data — always kept up to date automatically.</p>
          </button>
          <button type="button" onClick={() => selectVersion(true)} disabled={saving || content.trim().length === 0}
            className="text-left p-4 rounded-xl transition-all disabled:opacity-50"
            style={{
              background: enabled ? 'rgba(var(--kurso-primary-rgb), 0.1)' : 'rgba(255,255,255,0.02)',
              border: enabled ? '2px solid var(--kurso-primary)' : '1px solid rgba(255,255,255,0.08)',
            }}>
            <div className="flex items-center gap-2 mb-1">
              <p className="text-sm font-semibold text-white">Your Custom Version</p>
              {enabled && <Check className="w-4 h-4" style={{ color: 'var(--kurso-primary-light)' }} />}
            </div>
            <p className="text-xs" style={{ color: '#71717a' }}>
              {content.trim().length === 0 ? 'Add your custom page above first' : 'The version you pasted or uploaded above.'}
            </p>
          </button>
        </div>
        {savedMsg && (
          <p className="text-xs mt-3 flex items-center gap-1.5" style={{ color: '#22c55e' }}>
            <Check className="w-3.5 h-3.5" /> Saved
          </p>
        )}
        {error && (
          <p className="text-xs mt-3" style={{ color: '#ef4444' }}>{error}</p>
        )}
      </div>
    </div>
  )
}