import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

function safeCompare(a: string, b: string) {
  const left = Buffer.from(a)
  const right = Buffer.from(b)
  return left.length === right.length && crypto.timingSafeEqual(left, right)
}

function maxFreeLessons(config?: string) {
  if (config === 'lesson 1 free') return 1
  if (config === '2 lessons free') return 2
  if (config === '3 lessons free') return 3
  if (config === 'module 1 free') return 3
  if (config === '2 modules free') return 6
  return 0
}

function renderLessonHtml({
  title,
  contentUrl,
  contentType,
}: {
  title: string
  contentUrl: string
  contentType: string
}) {
  const escapedTitle = title.replace(/[<>&"]/g, char => ({
    '<': '&lt;',
    '>': '&gt;',
    '&': '&amp;',
    '"': '&quot;',
  }[char] || char))

  const isPdf = contentType === 'pdf'
  const player = isPdf
    ? `<iframe src="${contentUrl}" title="${escapedTitle}"></iframe>`
    : `<video controls controlsList="nodownload" src="${contentUrl}"></video>`

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="robots" content="noindex,nofollow" />
  <title>${escapedTitle}</title>
  <style>
    html,body{margin:0;background:#050505;color:#fff;font-family:system-ui,-apple-system,Segoe UI,sans-serif}
    main{min-height:100vh;display:flex;flex-direction:column}
    header{padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.08);font-size:14px;font-weight:700}
    .player{position:relative;flex:1;display:flex;align-items:center;justify-content:center;background:#000}
    video,iframe{width:100%;height:100%;border:0;max-height:calc(100vh - 52px)}
    .wm{position:absolute;left:12px;top:12px;padding:6px 9px;border-radius:8px;background:rgba(0,0,0,.55);border:1px solid rgba(255,255,255,.08);font-size:10px;letter-spacing:.08em;color:rgba(255,255,255,.7);pointer-events:none}
  </style>
</head>
<body>
  <main>
    <header>AcademyKit Protected Lesson</header>
    <section class="player">
      <div class="wm">ACADEMYKIT PROTECTED</div>
      ${player}
    </section>
  </main>
</body>
</html>`
}

export async function GET(req: NextRequest) {
  const url = new URL(req.url)
  const courseId = url.searchParams.get('courseId') || ''
  const lessonId = url.searchParams.get('lessonId') || ''
  const lesson = Number(url.searchParams.get('lesson') || '')
  const exp = Number(url.searchParams.get('exp') || '')
  const sig = url.searchParams.get('sig') || ''

  if (!courseId || !lessonId || !lesson || !exp || !sig) {
    return NextResponse.json({ error: 'Invalid lesson link' }, { status: 400 })
  }

  if (Date.now() > exp) {
    return NextResponse.json({ error: 'Lesson link expired' }, { status: 410 })
  }

  const secret = process.env.WHATSAPP_LINK_SECRET || process.env.VERIFY_TOKEN
  if (!secret) {
    return NextResponse.json({ error: 'Lesson links are not configured' }, { status: 500 })
  }

  const expected = crypto
    .createHmac('sha256', secret)
    .update(`${courseId}.${lessonId}.${lesson}.${exp}`)
    .digest('hex')

  if (!safeCompare(expected, sig)) {
    return NextResponse.json({ error: 'Invalid lesson signature' }, { status: 403 })
  }

  const [{ data: courseRows }, { data: lessonRows }] = await Promise.all([
    supabase.from('courses').select('id, name, free_preview_config').eq('id', courseId).limit(1),
    supabase.from('lessons').select('id, title, content_url, content_type, order_num, is_published').eq('id', lessonId).eq('course_id', courseId).limit(1),
  ])

  const course = courseRows?.[0]
  const lessonData = lessonRows?.[0]

  if (!course || !lessonData || !lessonData.is_published) {
    return NextResponse.json({ error: 'Lesson not found' }, { status: 404 })
  }

  if (lessonData.order_num > maxFreeLessons(course.free_preview_config)) {
    // Paid lessons are allowed here only through a signed WhatsApp link generated by the trusted bot.
    // The short expiry keeps the link shareable only for a limited window.
  }

  return new NextResponse(renderLessonHtml({
    title: lessonData.title,
    contentUrl: lessonData.content_url,
    contentType: lessonData.content_type,
  }), {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'private, no-store',
      'X-Robots-Tag': 'noindex, nofollow',
    },
  })
}
