/**
 * src/app/wa/my-courses/page.tsx
 * ─────────────────────────────────────────────────────────────────
 * "My Courses" for students who only ever talk to Kurso through
 * WhatsApp — no email/password account. Reached via a signed link
 * (lib/signer.ts signMyCoursesUrl) generated by the bot, verified
 * server-side by /api/whatsapp/my-courses.
 *
 * Read-only by design: continuing a lesson happens back on WhatsApp
 * (the bot already knows current_lesson and generates a fresh signed
 * lesson link), so each course card just deep-links back to WhatsApp
 * rather than duplicating that logic here.
 * ─────────────────────────────────────────────────────────────────
 */
'use client'

import { useEffect, useState, use } from 'react'
import { useSearchParams } from 'next/navigation'
import { BookOpen, MessageCircle, Shield } from 'lucide-react'

interface Course {
  enrollmentId: string
  courseId: string
  courseName: string
  courseSlug: string
  creatorName: string
  creatorSlug: string
  currentLesson: number
  completedCount: number
  totalLessons: number
  paymentStatus: string
}

function ProgressBar({ pct }: { pct: number }) {
  return (
    <div style={{ height: 6, borderRadius: 4, background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
      <div style={{
        height: '100%', width: `${pct}%`, borderRadius: 4,
        background: 'linear-gradient(90deg,var(--kurso-primary),var(--kurso-secondary))',
        transition: 'width 0.4s ease',
      }} />
    </div>
  )
}

export default function WhatsAppMyCoursesPage() {
  const searchParams = useSearchParams()
  const [courses, setCourses] = useState<Course[] | null>(null)
  const [invalid, setInvalid] = useState(false)
  const waNumber = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || ''

  useEffect(() => {
    async function load() {
      const identity = searchParams.get('identity') || ''
      const exp = searchParams.get('exp') || ''
      const sig = searchParams.get('sig') || ''

      if (!identity || !exp || !sig) {
        setInvalid(true)
        return
      }

      try {
        const params = new URLSearchParams({ identity, exp, sig })
        const res = await fetch(`/api/whatsapp/my-courses?${params.toString()}`)
        const json = await res.json()
        if (!res.ok || !json.valid) {
          setInvalid(true)
          return
        }
        setCourses(json.courses || [])
      } catch (e) {
        console.error('[wa/my-courses]', e)
        setInvalid(true)
      }
    }
    load()
  }, [searchParams])

  const waLink = waNumber ? `https://wa.me/${waNumber}?text=${encodeURIComponent('lesson')}` : ''

  if (invalid) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center px-6">
        <div className="max-w-sm text-center">
          <p className="text-red-400 mb-2 font-semibold">This link has expired or is invalid.</p>
          <p className="text-zinc-500 text-sm">Go back to WhatsApp and tap the My Courses button again for a fresh link.</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <header className="sticky top-0 z-20 border-b border-white/10 bg-black/90 backdrop-blur px-4 py-3">
        <div className="mx-auto max-w-2xl flex items-center justify-between gap-3">
          <span className="font-bold">📚 My Courses</span>
          <div className="inline-flex items-center gap-2 text-xs text-zinc-500">
            <Shield className="w-3.5 h-3.5" /> Kurso
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-2xl px-4 py-8 flex flex-col gap-4">
        {courses === null ? (
          [1, 2].map(i => (
            <div key={i} className="rounded-xl border border-white/10 p-5 animate-pulse">
              <div className="h-4 w-1/3 rounded bg-white/10 mb-3" />
              <div className="h-5 w-2/3 rounded bg-white/10" />
            </div>
          ))
        ) : courses.length === 0 ? (
          <div className="p-8 rounded-xl border border-white/10 bg-white/[0.03] text-center text-zinc-400">
            <BookOpen className="w-8 h-8 mx-auto mb-3 text-zinc-600" />
            No courses connected to this number yet.
          </div>
        ) : (
          courses.map(c => {
            const pct = c.totalLessons > 0 ? Math.min(Math.round((c.completedCount / c.totalLessons) * 100), 100) : 0
            return (
              <div key={c.enrollmentId} className="rounded-xl border border-white/10 bg-white/[0.03] p-5">
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div>
                    <p className="text-xs text-zinc-500">{c.creatorName}</p>
                    <h2 className="font-semibold text-lg">{c.courseName}</h2>
                  </div>
                  {c.paymentStatus !== 'paid' && (
                    <span className="text-xs px-2 py-1 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 flex-shrink-0">
                      Free preview
                    </span>
                  )}
                </div>
                <div className="flex items-center justify-between text-sm text-zinc-400 mb-2">
                  <span>{c.completedCount}/{c.totalLessons} lessons complete</span>
                  <span>{pct}%</span>
                </div>
                <ProgressBar pct={pct} />
                <p className="text-xs text-zinc-500 mt-3">Currently on Lesson {c.currentLesson}</p>
              </div>
            )
          })
        )}

        {waLink && (
          <a href={waLink}
            className="mt-2 inline-flex items-center justify-center gap-2 rounded-xl py-3 font-semibold text-white"
            style={{ background: 'linear-gradient(135deg,var(--kurso-primary),var(--kurso-secondary))' }}>
            <MessageCircle className="w-4 h-4" /> Continue on WhatsApp
          </a>
        )}
      </main>
    </div>
  )
}